### ISSUE TITLE
Penelope missing from webapps folder

### ISSUE THREAD

**Issue by billsanto** [OHDSI/Broadsea-WebTools#12]
The first line of the deploy-script references the penelope webapp, but it is not included in the webapps folder. If this app has been deprecated, should it be removed from the script?

root@a3b4f7729496:/usr/local/tomcat/webapps# ls
WebAPI	WebAPI.war  atlas

The beginning of the startup logs show:
broadsea-webtools Can't open /usr/local/tomcat/webapps/penelope/web/js/app.js: No such file or directory.

**Comment by leeevans** [comment]
@billsanto thanks for creating this issue - I have removed that line from the deploy-script
