### ISSUE TITLE
Custom settings.xml

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/Broadsea-WebTools#8]
How can I easily override settings (e.g. security settings) from the WebAPI settings.xml file using this Docker container?

**Comment by shandy79** [comment]
There are definitely some elements of the settings.xml file that can be overridden using the docker-compose.yml file, e.g., https://github.com/OHDSI/Broadsea/blob/master/postgresql/docker-compose.yml, but I'm not sure how much of it can be replaced that way.  In particular, I'm interested in custom elements for security.

**Comment by shailender1984** [comment]
@leeevans,
could you please confirm if we can override the ldap authentication through docker-compose file ??
as I am trying it but ldap is not working. How can we update the settings.xml  ?
could you please update the images with ldap authentication ?
